# Generated by Django 4.2.2 on 2023-09-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.DateField(auto_now=True),
        ),
    ]
